### ISSUE TITLE
Policies: Write-Access only for a subdirectory of a bucket is broken

### ISSUE THREAD

**Issue by karlludwigweise** [minio/console#2155] opened 2022-06-29 13:20 UTC
### Current behaviour

With this policy implemented, it is impossible to upload a file to `pathWithWriteAccess`:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/*"
            ]
        },
        {
            "Effect": "Deny",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/pathWithReadAccess/*"
            ]
        },
        {
            "Effect": "Deny",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/pathWithWriteAccess/*"
            ]
        }
    ]
}
```

* the front-end of the console actually enables and disables the "Upload File" button accordingly
* the back-end of the console rejects the upload POST (via the front-end) with `500 Internal Server Error` and the following body:
```
{
  "code":500,
  "detailedMessage":"Access Denied.",
  "message":"an error occurred, please try again"
}
```

This is reproducibale on RELEASE.2022-06-25T15-50-16Z

### Expected behaviour

Granting write access to only sub-routes of a bucket should be possible.

### Additional notes

* This issue might be related to https://github.com/minio/console/issues/2104
* I'm trying to configure a policy that gives write access only to a sub-path of a bucket

**Comment by Alevsk** [comment] 2022-07-25 17:12
I'm trying to reproduce and work on a fix for this today

**Comment by Alevsk** [comment] 2022-07-25 18:28
@karlludwigweise tried to reproduce the issue, `bucketName` needs to be `bucketname` since buckets cannot contain uppercase, then I tried to upload the file via Console UI and got the error.

@harshavardhana I tried to upload the file to the writable path via mc and got the error as well

```
mc cp README.md myminio/bucketname/pathWithWriteAccess/README.md
mc: <ERROR> Failed to copy `/home/alevsk/Development/kind/README.md`. Insufficient permissions to access this file `http://localhost:9000/bucketname/pathWithWriteAccess/README.md`
```

I think the problem is the deny rule at the bucket top level is affecting the subpath

```
{
            "Effect": "Deny",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketName/pathWithWriteAccess/*"
            ]
        }
        ```

**Comment by karlludwigweise** [comment] 2022-07-26 09:05
@Alevsk thanks for checking it out. Glad you can reproduce it. `bucketName` in camelCase was just for illustration purposes.

**Comment by harshavardhana** [comment] 2022-08-06 05:57
> {
>             "Effect": "Deny",
>             "Action": [
>                 "s3:AbortMultipartUpload",
>                 "s3:ListBucketMultipartUploads",
>                 "s3:ListMultipartUploadParts",
>                 "s3:PutObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::bucketName/*"
>             ]
>         },
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "s3:AbortMultipartUpload",
>                 "s3:ListBucketMultipartUploads",
>                 "s3:ListMultipartUploadParts",
>                 "s3:PutObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::bucketName/pathWithWriteAccess/*"
>             ]
>         }

This is impossible to provide in IAM policy language due to implicit deny your first resource 
automatically matches any request to the `pathWithWriteAccess/*` 

Whatever the behavior here is expected you should re-do your IAM policy.

**Closed by harshavardhana** 2022-08-06 05:57 UTC

**Comment by karlludwigweise** [comment] 2022-08-08 12:42
@harshavardhana what would be a valid way to configure a IAM policy where a user can only write to a sub-path of a bucket?

**Comment by karlludwigweise** [comment] 2022-08-09 10:19
@harshavardhana thanks!

Anyone coming here in search for a policy that only grants access to parts of a bucket:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname/readonly/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname/readwrite/*"
            ]
        }
    ]
}
```
