### ISSUE TITLE
Little bug leads to page crash

### ISSUE THREAD

**Issue by geektheripper** [minio/console#2825] opened 2023-05-21 05:07 UTC
https://github.com/minio/console/blob/629dd669c4970fbc89ac97ba254a88a280a4dbaf/portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx#L311-L313

should be:

```ts
 usage?.backend?.rrSCParity
   ? usage.backend.rrSCParity.toString() 
   : "n/a" 
```

**Comment by harshavardhana** [comment] 2023-05-21 06:33
Please send a PR @geektheripper thank you..

**Comment by geektheripper** [comment] 2023-05-21 07:51
> Please send a PR @geektheripper thank you..

#2826 done

**Comment by bexsoft** [comment] 2023-05-23 00:29
PR Merged, Thank you very much for your contribution. This will be available in the next Console release.

Please let us know if the issue is still visible after this change so we can take a look.

**Closed by bexsoft** 2023-05-23 00:29 UTC
