### ISSUE TITLE
MInio console UI page refresh issue 

### ISSUE THREAD

**Issue by balaKarur** [minio/console#3274] opened 2024-03-27 08:49 UTC
## NOTE

Hello All,
**Issue**:
Getting refresh issue while access minio Console UI, Please refer attached image...
I faced this issue in both minio (windows and linux version )
To check minio windows version : [https://min.io/download#/agpl-windows]

## Expected Behavior

while access minio console UI , logion page has to shown ,without multiple refresh .
[http://localhost:9001/](url)
## Current Behavior

Need to refresh many time to get login page , after login successful , again need to refresh many time to get landing page 

## Possible Solution

Need a suggestion to fix this 
**## Steps to Reproduce (for bugs)**

This is windows minio ,
https://min.io/download#/agpl-windows
 Just download and run the server you will face refresh issue while access the URL 
[http://localhost:9001/](url)

**## Context**

I need to use minio server, for to upload files under bucket .
**## Regression**

I think .its Regression, and straightforward issue 
## Your Environment

* MinIO version used (`minio --version`): RELEASE.2024-03-21T23-13-43Z
* Server setup and configuration:
* Operating System and version (`uname -a`): ubuntu20 access thur wsl
**This my setup :**
**I am using latest keycloak and minio service
I followed to**
1)Configure MinIO for Authentication using Keycloak
https://min.io/docs/minio/linux/operations/external-iam/configure-keycloak-identity-management.html
2)https://min.io/docs/minio/linux/reference/minio-server/settings/iam/openid.html#redirect-uri
This is my yaml file
version: "3.8"
services:
    minio:
        image: [quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z](http://quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z)
        container_name: minio
        volumes:
          - ./minio_data:/data
        command: server /data --console-address=":9001"
        ports:
          - 9000:9000
          - 9001:9001
        environment:
          - MINIO_ROOT_USER=admin
          - MINIO_ROOT_PASSWORD=password
          - MINIO_SERVER_URL=http://localhost:9000/
          - MINIO_DOMAIN=http://localhost:9000/
          - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=http://host.containers.internal:8088/kc/realms/demorealm/.well-known/openid-configuration
          - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=minio
          - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=SymWPBfZVz4qJoC7MevG63Sat
          - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=MinIO OpenID Login
          #- MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY=openid,preferred_username
          - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
          - MINIO_IDENTITY_OPENID_VENDOR=keycloak
          - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=on
          - MINIO_IDENTITY_OPENID_SCOPES=minio-authorization
          - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=demorealm
          - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://host.containers.internal:8088/kc/admin
          #- MINIO_BROWSER_REDIRECT_URL=http://localhost:9000/minio-console
    #      - CONSOLE_SUBPATH=/minio-console
          #- CONSOLE_MINIO_SERVER=http://localhost:9000/
          #- MINIO_API_SELECT_PARQUET=on
        # restart: always
volumes:
    minio_data: (edited)
![refresh](https://github.com/minio/console/assets/13732401/20a77eb0-b7a5-4a0a-8463-1718d2f23681)

**Comment by cesnietor** [comment] 2024-04-01 16:49
@balaKarur  could you please share your keycloak configuration, there might be an issue there. 
cc @adriangitvitz

**Comment by balaKarur** [comment] 2024-04-08 07:08
Hello @cesnietor 
i am getting issue without keycloak integration also

I tried with windows version from below URL
https://min.io/download#/agpl-windows

_By following these steps :_
**PS> Invoke-WebRequest -Uri "https://dl.min.io/server/minio/release/windows-amd64/minio.exe" -OutFile "C:\minio.exe"
PS> setx MINIO_ROOT_USER admin
PS> setx MINIO_ROOT_PASSWORD password
PS> C:\minio.exe server F:\Data --console-address ":9001"**

I notioced issue exist in 2 place , 
1)while accessing  login page URL. http://localhost:9001
2)while switching inside the bucket http://localhost:9001/browser/bk1

**Comment by balaKarur** [comment] 2024-04-10 06:02
Hello @cesnietor @adriangitvitz
Could you please check for a refresh issue on the Windows version?

**Comment by adriangitvitz** [comment] 2024-04-10 17:40
using this configuration with docker works, could you provide your keycloak configuration ? and also are the containers reachable ?

```
version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z
    container_name: minio
    volumes:
      - ./minio_data:/data
    command: server /data --console-address=":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Pa55w0rd
      - MINIO_SERVER_URL=http://localhost:9000/
      - MINIO_DOMAIN=http://localhost:9000/
      - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=http://host.docker.internal:8080/realms/consoletest/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=6FJmGUdCBbhiDUJCLTZ8zKzqIh6YOC4X
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=MinIO OpenID Login
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
      - MINIO_IDENTITY_OPENID_VENDOR=keycloak
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=on
      - MINIO_IDENTITY_OPENID_SCOPES=minio-authorization
      - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=consoletest
      - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://host.docker.internal:8080/admin
```

**Comment by balaKarur** [comment] 2024-04-18 14:25
@adriangitvitz 
"using this configuration with docker works, could you provide your keycloak configuration ? and also are the containers reachable ?"
Thank you for your effort. As I confirmed, the issue is not related to Keycloak. Once Minio is up, did you get time to check if the Minio console UI is accessible by accessing this URL: http://localhost:9001/ without having to refresh multiple times?

I noticed the refresh issue exists in two places:

While accessing the login page URL: http://localhost:9001/
While switching inside the bucket: http://localhost:9001/browser/bk1

**Comment by balaKarur** [comment] 2024-05-06 06:15
@adriangitvitz 
      I hope this message finds you well. Did you get the time to check the reported issue above? If not, could you please take a moment to review it? Thank you.

**Comment by adriangitvitz** [comment] 2024-05-06 14:09
Hi, I don't see the refresh issue while accessing http://localhost:9001/ or  http://localhost:9001/browser/bk1, using the previous docker compose configuration.

https://github.com/minio/console/assets/39295224/db036864-87ea-4ef8-95ed-4c398d792963

**Comment by cesnietor** [comment] 2024-05-06 16:40
> could you provide your keycloak configuration 

@balaKarur we'd need to see your configuration otherwise it's not possible for us to reproduce this.

**Comment by balaKarur** [comment] 2024-05-08 10:43
Hello  @cesnietor  @adriangitvitz ,
   Thanks for your continuous support. i attached keycloak configuration, Please check  
   [Update keyclock with minio configurations.docx](https://github.com/minio/console/files/15247698/Update.keyclock.with.minio.configurations.docx)
   
   Please let me know if you need any other info.

**Comment by balaKarur** [comment] 2024-05-13 19:18
Hello @cesnietor @adriangitvitz ,
Thanks for your continuous support. If you have some free time, could you please check my configuration?

**Comment by adriangitvitz** [comment] 2024-05-15 05:37
@balaKarur please try with the following and let me know, in the home url, after "realms", use your realm name

![Screenshot 2024-05-14 at 11 35 01 p m](https://github.com/minio/console/assets/39295224/effb0498-b68e-4911-84d7-902eef9208b9)

**Comment by balaKarur** [comment] 2024-05-21 07:02
Hello, @cesnietor, @adriangitvitz ,
Thank you for your support, and I apologize for the delay in my reply.
I tried the way you suggested, but it did not help that solution. Still, I need to refresh multiple times to get login page 
A small request: can we connect through Google Meet? to solve this issue?
please let me know when you have free time , 
![image](https://github.com/minio/console/assets/13732401/f54e43b3-6808-4a37-bef1-f4a603795368)

Thanks 
Balasubramani.V

**Comment by prakashsvmx** [comment] 2024-05-21 07:04
We request you to consider min.io/pricing @balaKarur .

**Comment by cesnietor** [comment] 2024-05-29 16:54
@balaKarur  please refer to what @adriangitvitz  suggested.
For more Keycloak configuration support please refer to their page.
Also feel free to use our Slack channel where other community members might be able to help you with support.
For more immediate help definitely consider subscribing to SUBNET (min.io/pricing).
Closing since this is a configuration issue and not a bug.

**Closed by cesnietor** 2024-05-29 16:54 UTC
Labels: community, triage

**Comment by balaKarur** [comment] 2024-06-05 10:47
Hello, @cesnietor, @adriangitvitz ,,
  Thank you so much for your tremendous support. I resolved this issue...
