### ISSUE TITLE
This 'admin' API is not supported by server in 'mode-server-fs'

### ISSUE THREAD

**Issue by capriciousduck** [minio/console#863] opened 2021-07-13 10:48 UTC
I am getting the following error after bucket creation. Please look into it. This is the error.

This 'admin' API is not supported by server in 'mode-server-fs'

**Comment by harshavardhana** [comment] 2021-07-13 16:33
This is part of an overhaul needed to handle certain missing APIs in single drive mode and gateway needed.

**Comment by hmwdt** [comment] 2021-07-16 07:05
me too , same problem！！

**Comment by harshavardhana** [comment] 2021-07-16 18:18
Closing as duplicate of #723

**Closed by harshavardhana** 2021-07-16 18:18 UTC
