### ISSUE TITLE
Return proper error codes if minIO server returns error

### ISSUE THREAD

**Issue by cesnietor** [minio/console#98] opened 2020-05-06 19:11 UTC
Today any error happening on minIO server we send it as `500` we need to handle them properly in case there is for instance a `400` or a `401` for access denied, etc.

**Comment by bexsoft** [comment] 2020-05-07 23:00
Duplicated from #18

**Comment by jaredkipe** [comment] 2020-06-27 00:33
Speaking of... I am getting a 401 with message body like "Error: {"code":401,"message":"an error occurred, please try again"}" in red when trying to login.

Seems related, though I'm only seeing an error in the log like this. (out of MCS when attempting login)
```
2020/06/27 00:05:19 
    error obtaining MinIO region: Get https://minio.dev1.hiboucorp.com/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
```

I'm getting reasonable looking responses in the ingress itself (which has improved my debugging of the error for sure).  (note the timestamps are identical)

```
    10.3.14.22 - - [27/Jun/2020:00:04:17 +0000] "GET /api/v1/login HTTP/2.0" 200 25 "https://admin.minio.dev1.hiboucorp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 64 0.001 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 25 0.000 200 23d9e4853ac9dd769e37dc85b0d25e87
6/26/2020 5:05:19 PM
    10.3.14.22 - - [27/Jun/2020:00:05:19 +0000] "POST /api/v1/login HTTP/2.0" 401 61 "https://admin.minio.dev1.hiboucorp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 129 47.235 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 61 47.236 401 613e4abba66841b2d57e76c4f76d42f8
```

Before forcing it through the ingress controller, I would also get errors like the following, (which was eliminated by utilizing nginx ingress controller to "wash" through SSL with `nginx.ingress.kubernetes.io/backend-protocol="HTTPS"` and default "proxy-ssl-verify" is "off")  For what it is worth, the certificate used by minio has been a perfectly valid DNS01 obtained letsencrypt certificate.


```
    API: SYSTEM()
6/26/2020 4:37:35 PM 
    Time: 23:37:35 UTC 06/26/2020
6/26/2020 4:37:35 PM 
    DeploymentID: 93eebf08-f47d-4695-bdee-9ec706c9dcc2
6/26/2020 4:37:35 PM 
    Error: http: TLS handshake error from 10.42.2.46:42058: remote error: tls: bad certificate
6/26/2020 4:37:35 PM 
           1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
```


So all that said, maybe I'm just getting a 401, what credentials should I be using on that panel? I've been trying to use my minio main secrets, which work fine through ingress controller and the built in minio browser.

**Comment by dvaldivia** [comment] 2020-06-27 00:37
@jaredkipe the MinIO Root Credentials (main credentials) are the only ones that don't support STS Tokens, therefore you cannot login with them. Create a user account with `admin:*` capabilities and use it to login instead, I think we have an example on the readme

**Comment by jaredkipe** [comment] 2020-06-27 01:24
Oh shoot, that explains that!

So I added my user, you can see it in the ingress logs.

```
10.3.14.33 - - [27/Jun/2020:01:07:59 +0000] "PUT /minio/admin/v3/add-user?accessKey=jared HTTP/1.1" 200 0 "-" "MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-06-26T19:56:55Z" 608 0.207 [minio-system-minio-service-9000] [] 10.42.3.39:9000 0 0.208 200 2d064e65f28e943e6f67eb683b65ee07
6/26/2020 6:09:20 PM 
    10.3.14.33 - - [27/Jun/2020:01:09:20 +0000] "PUT /minio/admin/v3/add-canned-policy?name=admin HTTP/1.1" 200 0 "-" "MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-06-26T19:56:55Z" 655 0.132 [minio-system-minio-service-9000] [] 10.42.1.41:9000 0 0.132 200 af2c7a0d4aca9bd130a30e91c062ae64
6/26/2020 6:09:32 PM 
    10.3.14.33 - - [27/Jun/2020:01:09:32 +0000] "PUT /minio/admin/v3/set-user-or-group-policy?isGroup=false&policyName=admin&userOrGroup=jared HTTP/1.1" 200 0 "-" "MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-06-26T19:56:55Z" 567 0.110 [minio-system-minio-service-9000] [] 10.42.1.41:9000 0 0.108 200 30be3e6469a95838efb786486a4b599f


6/26/2020 6:11:29 PM 
    10.3.14.22 - - [27/Jun/2020:01:11:29 +0000] "POST /api/v1/login HTTP/2.0" 502 158 "https://admin.minio.dev1.hiboucorp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 284 105.838 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 0 105.840 502 fabd2df537c14c40212f41abcd655a8a
6/26/2020 6:12:44 PM 
    10.3.14.22 - - [27/Jun/2020:01:12:44 +0000] "GET / HTTP/2.0" 200 1272 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 57 0.004 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 2653 0.004 200 0c56d6ea84c4a8738deb9d82fd1ad666
6/26/2020 6:12:44 PM 
    10.3.14.22 - - [27/Jun/2020:01:12:44 +0000] "GET /api/v1/login HTTP/2.0" 200 25 "https://admin.minio.dev1.hiboucorp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 31 0.000 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 25 0.004 200 8f57cf623d8c0ecf785f539f1df8ffb7
6/26/2020 6:15:43 PM 
    2020/06/27 01:15:43 [error] 2298#2298: *1397028 upstream prematurely closed connection while reading response header from upstream, client: 10.3.14.22, server: admin.minio.dev1.hiboucorp.com, request: "POST /api/v1/login HTTP/2.0", upstream: "https://10.42.2.47:9443/api/v1/login", host: "admin.minio.dev1.hiboucorp.com", referrer: "https://admin.minio.dev1.hiboucorp.com/"
6/26/2020 6:15:43 PM 
    10.3.14.22 - - [27/Jun/2020:01:15:43 +0000] "POST /api/v1/login HTTP/2.0" 502 158 "https://admin.minio.dev1.hiboucorp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15" 73 85.548 [minio-system-minio-mcs-https-mcs] [] 10.42.2.47:9443 0 85.548 502 74ebe2b1eff3dbf5a60400e91a5eb7c2
```

So something else is wrong, most likely the earlier
`error obtaining MinIO region: Get https://minio.dev1.hiboucorp.com/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority`

So if I take that url into a sidecar and `curl it`, I receive this.

`{"Code":"XMinioAdminVersionMismatch","Message":"This 'admin' API is not supported by server in 'mode-server-distributed-xl'","Resource":"/minio/admin/v3/help-config-kv","RequestId":"","HostId":"93eebf08-f47d-4695-bdee-9ec706c9dcc2"}`

Which certainly looks like progress, but would still need to change in MCS to fix, correct?

**Comment by harshavardhana** [comment] 2020-06-27 12:10
Your server version is too old for mcs @jaredkipe

**Comment by jaredkipe** [comment] 2020-06-27 12:54
@harshavardhana  The minio server that was provisioned by `minio/minio-operator` yesterday and dated 9 days ago is too old? `minio/minio:RELEASE.2020-06-18T02-23-35Z`

**Comment by jaredkipe** [comment] 2020-06-27 13:23
I also just realized that the README.md file's environment variable `MCS_MINIO_SERVER_TLS_SKIP_VERIFICATION` does not appear to be used anywhere.  Shouldn't matter to me because I'm not using self-signed certificates, but it is interesting and could help explain why the log in `mcs` is always complaining about that.

Just to reiterate for myself, I tried connecting `mcs` directly to minio (not through ingress) and `minio` itself complains about TLS handshake error.

**Comment by jaredkipe** [comment] 2020-06-27 14:38
My issue is caused by the `Dockerfile.release` NOT installing and copying CA certs.  I built my own and they do not suffer this issue.  `hibou/mcs:v0.1.0` and `hibou/mcs:v0.1.1`

New issue.  When I try to login with bad credentials, I see the red bad credentials message.  When I try to log in with good credentials, the page refreshes with nothing in the logs.  (logs do have various errors when supplying bad credentials.)

**Comment by jaredkipe** [comment] 2020-06-27 15:46
My final issue was Safari caused (#184)

**Comment by dvaldivia** [comment] 2020-10-30 05:25
@Alevsk do you think this has been addressed with your PR that returned more detailed errors?

**Comment by Alevsk** [comment] 2020-10-30 20:20
> @Alevsk do you think this has been addressed with your PR that returned more detailed errors?

Yes, in the case of the login endpoint, if there's an error in the backend user will always see 'invalid credentials' in the frontend, this is to prevent user enumeration, etc @jaredkipe if you see any errors during user logging please look at the console logs, you will see there more detailed information there.

Im closing this, please re-open if you see any more errors.

**Closed by Alevsk** 2020-10-30 20:20 UTC
Labels: enhancement
