### ISSUE TITLE
[Operator UI] SSO login issue with IDP configured

### ISSUE THREAD

**Issue by sylvainOL** [minio/console#2449] opened 2022-11-10 10:13 UTC
Hello,

I'm using helm release of operator to deploy minio operator and console on top on a cluster with istio

with version `4.5.3`, everything is fine and it deploys minio console `v0.21.0`.

I've got the following config for OIDC on console:

```yaml
    spec:
      containers:
      - args:
        - server
        env:
        - name: CONSOLE_OPERATOR_MODE
          value: "on"
        - name: CONSOLE_MINIO_SERVER
          value: http://operator.minio-system.svc.cluster.local:4222
        - name: CONSOLE_IDP_URL
          value: https://keycloak.fqdn/realms/mine/.well-known/openid-configuration
        - name: CONSOLE_IDP_CLIENT_ID
          value: istio
        - name: CONSOLE_IDP_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: minio-istio
        - name: CONSOLE_IDP_CALLBACK
          value: https://minio.fqdn/oauth_callback
        image: minio/console:v0.21.0
```

when moving to version `4.5.4`, it tries to deploy console `v0.21.1` and I've got the following error:

`Invalid number of tokens, expected only 2, got 3 instead`.

I've checked also with version `v0.21.2` and I've got the same issue.

I looked at requests and seen that `POST` on auth has a different behavior:

with version `v0.21.0`, state param has the following value:

`MlhVMUZNWVRBVEFETEc1T1VJNFFQQUgyUzp1TzJNbHFCQ0JHdmVueGdvVHo3L01jb3N2aml2TGV5clUvNk8zTlBvNjJRPQ==`

which base64 decode to:

`2XU1FMYTATADLG5OUI4QPAH2S:uO2MlqBCBGvenxgoTz7/McosvjivLeyrU/6O3NPo62Q=`(values have been changed)

with version `v0.21.1` or `v0.21.2`, the state param has the following value:

`eyJzdGF0ZSI6IlJWQXhWVFJRVnpKTVExVk1SekpNTWxWTVRWY3lNMWhJVkRwd1dWaHJVVkoyYkhneGFIWnliM1JuZUVWQlpVdDBaRkpwU0ZCd1dESk1WR0ZaZVdGVU9WSlRSRU5WUFE9PSIsImlkcF9uYW1lIjoiaXN0aW8ifQ==`

wich base64 decode to:

```json
{"state":"RVAxVTRQVzJMQ1VMRzJMMlVMTVcyM1hIVDpwWVhrUVJ2bHgxaHZyb3RneEVBZUt0ZFJpSFBwWDJMVGFZeWFUOVJTRENVPQ==","idp_name":"istio"}
```

and `state` in `state` base64 decode to: 

`EP1U4PW2LCULG2L2ULMW23XHT:pYXkQRvlx1hvrotgxEAeKtdRiHPpX2LTaYyaT9RSDCU=`

so I guess there has been a change somewhere that breaks with my config.

Can you help me to see how I can move to the new version?

**Comment by sylvainOL** [comment] 2022-11-10 13:04
I think the issue comes from this change no?

https://github.com/minio/console/compare/v0.21.0..v0.21.1#diff-f918c242ae26e2baf95e6f958b71356a99f88c5fc68fecda5a7ecda1302435ceR58

**Comment by bexsoft** [comment] 2022-11-17 21:16
Hi @sylvainOL!

This issue seems to be more related to Operator & IDP, We will take a look

**Comment by sylvainOL** [comment] 2022-11-18 07:01
Hi @bexsoft!

Yes it's related to operator, sorry I forgot to say!
I can add other env variables if needed to test / check it works!

don't hesitate to ask!

**Comment by sylvainOL** [comment] 2022-12-13 07:24
Hello, any news on this? I'd love to bump minio operator version but can't because of this issue :(

**Comment by reivaj05** [comment] 2022-12-21 18:31
Hi @sylvainOL, i'm currently working on this, I was able to reproduce the issue, now i just need to find the root cause and fix it. 
Should be fixed soon

**Comment by sylvainOL** [comment] 2022-12-21 20:04
Hi @reivaj05, awesome, thank you!

**Closed** 2023-01-03 18:35 UTC
Labels: bug

**Comment by sylvainOL** [comment] 2023-02-28 07:42
Hello @reivaj05, I miss the fact you resolved it.
I've just checked and it works :)

thanks!
