### ISSUE TITLE
Please, add text to README.md warning users why they were suddenly redirected to this project

### ISSUE THREAD

**Issue by juliohm1978** [minio/console#716] opened 2021-05-04 01:04 UTC
Directly related to https://github.com/minio/minio/pull/12172.

Me and my team spent an entire afternoon trying to figure out why the hell our brand new minio instances keep redirecting to https://github.com/minio/console without any explanation whatsoever. Not even a single warning in the logs. No clear explanation in official docs, not even a remark in the console project's README.md. We honestly thought the image was broken :smile: 

Strangely, visiting http://127.0.0.1:9000 still shows the console, so that added to the confusion.

**Comment by harshavardhana** [comment] 2021-05-04 01:39
> Me and my team spent an entire afternoon trying to figure out why the hell our brand new minio instances keep redirecting to https://github.com/minio/console without any explanation whatsoever. Not even a single warning in the logs. No clear explanation in official docs, not even a remark in the console project's README.md. We honestly thought the image was broken

This change was reverted, you are not advised to use master branch code - we haven't even made any release of the code. Current master is not doing that anymore closing.

**Closed by harshavardhana** 2021-05-04 01:39 UTC

**Comment by gerwim** [comment] 2021-05-04 11:05
I was not aware of this either. Both the `minio/minio` Docker image and the `minio/minio:RELEASE.2021-04-27T23-46-03Z.release.0033eb96` image redirect to this project.

I had to check the merge requests in the minio project to find out the embedded browser was removed 7 days ago. Adding a headsup to this project's README about why we're redirected here would be great :-).

**Comment by harshavardhana** [comment] 2021-05-04 15:36
> I was not aware of this either. Both the `minio/minio` Docker image and the `minio/minio:RELEASE.2021-04-27T23-46-03Z.release.0033eb96` image redirect to this project.
> 
> I had to check the merge requests in the minio project to find out the embedded browser was removed 7 days ago. Adding a headsup to this project's README about why we're redirected here would be great :-).

Latest shouldn't be updated, only edge would change and also 

> minio/minio:RELEASE.2021-04-27T23-46-03Z.release.0033eb96 

And this is an internal build - I don't know why you would use it. It's not the released binary yet.

**Comment by juliohm1978** [comment] 2021-05-04 21:02
Yes, confirmed.

The official release does not have this behavior. The image tags are bit confusing, though :smile:

From docker hub itself, there is no indication and you need to browser through the release page to figure out which one you should  use.

**Comment by theswordsmahin** [comment] 2021-05-27 00:34
@harshavardhana 

I just hit this as well, and I'm hoping you can provide me with some assistance. You mentioned:
> Latest shouldn't be updated, only edge would change and also

But I'm also seeing this on 
- minio/minio:latest, 
- minio/minio:RELEASE.2021-05-22T02-34-39Z, 
- minio/minio:RELEASE.2021-05-26T00-22-46Z

Maybe I am missing something, but can you point me to where the list of releases that we actually should use are clearly laid out? As @juliohm1978 mentioned, dockerhub is not very clear, and those other RELEASE tags I tried were taken from GitHub releases, so I'm not sure what else to use. 

Thank you very much in advance

**Comment by theswordsmahin** [comment] 2021-05-27 17:30
My apologies, it seems that after I used an improper docker image the browser cached the redirection and all attempts on other images would continue to redirect here. Using an incognito tab worked as expected and subsequently clearing my browsing data restored the expected behavior. Thank you for your time

**Comment by pgassmann** [comment] 2021-05-31 09:10
> > minio/minio:RELEASE.2021-04-27T23-46-03Z.release.0033eb96
> 
> And this is an internal build - I don't know why you would use it. It's not the released binary yet.

@harshavardhana that tag contains RELEASE, event twice. how should we know that this is not an actual release?

Which of the docker tags are actual stable releases with a fixed version? https://hub.docker.com/r/minio/minio/tags?page=1&ordering=last_updated

**Comment by pgassmann** [comment] 2021-05-31 09:30
Note: not only the console was redirected but also links to public objects https://minio.example.com/bucket/object.gif

The tags in the form RELEASE.2021-05-26T00-22-46Z without appendix seem to be the official releases. matching the tag names of https://github.com/minio/minio/releases

**Comment by harshavardhana** [comment] 2021-05-31 14:59
> > > minio/minio:RELEASE.2021-04-27T23-46-03Z.release.0033eb96
> > 
> > And this is an internal build - I don't know why you would use it. It's not the released binary yet.
> 
> @harshavardhana that tag contains RELEASE, event twice. how should we know that this is not an actual release?
> 

You should pick them based on the release tags on GitHub these are for internal purposes and we have never mentioned that you can go ahead use whatever tags are available in docker on our local deployment
.

> Which of the docker tags are actual stable releases with a fixed version? https://hub.docker.com/r/minio/minio/tags?page=1&ordering=last_updated

All of them as mentioned https://github.com/minio/minio/releases

**Comment by theswordsmahin** [comment] 2021-05-31 17:15
@harshavardhana At least for me, I typically just browse through the pages on dockerhub and grab a recent tag for images I'm interested in, so I just assumed these were meant for public use since they had RELEASE in the name. I don't think this is really an atypical practice, especially if you do not want to be grabbing latest, and might be worth some clarification on the dockerhub page. For example: https://hub.docker.com/_/ubuntu?tab=description&page=1&ordering=last_updated clearly lists supported tags. Just a thought. 
But thank you for the information, I at least won't make the mistake again.

**Comment by juliohm1978** [comment] 2021-05-31 17:17
Not marking unstable tags with the name "RELEASE" will be welcome :)
