### ISSUE TITLE
Lastest version, minio console web tools has bug?

### ISSUE THREAD

**Issue by hmwdt** [minio/console#873] opened 2021-07-16 07:22 UTC
use docker , I pull the lastest version. It can start the system . But the minio console has some problems.

1.unknow error
<img width="847" alt="1" src="https://user-images.githubusercontent.com/27841545/125908219-c6570d1e-0c80-41c4-a18f-52f18cd75d6b.png">

2.This 'admin' API is not supported by server in 'mode-server-fs'
<img width="1099" alt="2" src="https://user-images.githubusercontent.com/27841545/125908241-e8a383bd-38d5-4db9-97de-cbf2111b5c01.png">

3.can not share
<img width="1077" alt="3" src="https://user-images.githubusercontent.com/27841545/125908257-2d59ff97-78cb-473c-927f-22ecf1f9bd6e.png">

**Comment by hmwdt** [comment] 2021-07-16 07:24
Who can help me？😂

**Comment by harshavardhana** [comment] 2021-07-16 07:57
There is no error @hmwdt console is not fully supported on single drive (FS) mode

**Comment by harshavardhana** [comment] 2021-07-16 07:58
Closing as duplicate of https://github.com/minio/console/issues/863

**Closed by harshavardhana** 2021-07-16 07:58 UTC

**Comment by vavra7** [comment] 2021-07-17 10:23
> There is no error @hmwdt console is not fully supported on single drive (FS) mode

I just try minio for the first time and hit this issue right the way. Does it mean that Minio console is not for me if I intend to use minio in single drive (FS) mode only?

**Comment by harshavardhana** [comment] 2021-07-17 14:13
> > There is no error @hmwdt console is not fully supported on single drive (FS) mode
> 
> I just try minio for the first time and hit this issue right the way. Does it mean that Minio console is not for me if I intend to use minio in single drive (FS) mode only?

It's being addressed here #874

**Comment by hmwdt** [comment] 2021-07-17 14:20
@harshavardhana @vavra7 
This is what I do. You can refer to it !
`docker run --restart always -d -p 9000:9000 -p 9001:9001 --name minio -v /home/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" minio/minio server /data/data-1 /data/data-2 /data/data-3 /data/data-4 --console-address ":9001"
`

**Comment by harshavardhana** [comment] 2021-07-17 14:22
> @harshavardhana @vavra7 
> This is what I do. You can refer to it !
> `docker run --restart always -d -p 9000:9000 -p 9001:9001 --name minio -v /home/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" minio/minio server /data/data-1 /data/data-2 /data/data-3 /data/data-4 --console-address ":9001"
> `
> 
> 

> docker run --restart always -d -p 9000:9000 -p 9001:9001 --name minio -v /home/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" minio/minio server /data/data-{1...4} --console-address ":9001"

Slightly simpler version

**Comment by hmwdt** [comment] 2021-07-17 14:24
@harshavardhana 
Thank you. I'll try

**Comment by vavra7** [comment] 2021-07-17 15:21
> > @harshavardhana @vavra7
> > This is what I do. You can refer to it !
> > `docker run --restart always -d -p 9000:9000 -p 9001:9001 --name minio -v /home/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" minio/minio server /data/data-1 /data/data-2 /data/data-3 /data/data-4 --console-address ":9001" `
> 
> docker run --restart always -d -p 9000:9000 -p 9001:9001 --name minio -v /home/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" minio/minio server /data/data-{1...4} --console-address ":9001"
> 
> Slightly simpler version

Ok, I am really confused what the command `server /data/data-{1...4} --console-address ":9001"` does but it seems that did the trick. Thank you

**Comment by si458** [comment] 2021-07-18 17:59
@vavra7 basically using this multi directory command, it uses the erasure method of storing your data,
so 3 times the data (and storage) but if one folder dies/has errors, it will carry on working like nothing happened
PLUS you get extra features too like file versions, locking, etc...
https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html
