### ISSUE TITLE
Can't view/tag/share files inside bucket.

### ISSUE THREAD

**Issue by arantesxyz** [minio/console#654] opened 2021-03-18 02:02 UTC
I can't view, tag or share files inside a bucket in `User -> Object Browser -> MyBucket -> file.png`

UI error:
![Screen Shot 2021-03-17 at 22 58 58](https://user-images.githubusercontent.com/42740492/111562186-84dd8c00-8774-11eb-9a82-dd43c6ea6fd0.png)

Browser errors:
![Screen Shot 2021-03-17 at 22 59 23](https://user-images.githubusercontent.com/42740492/111562192-85762280-8774-11eb-88a0-569c2d12d488.png)

Container logs:
![Screen Shot 2021-03-17 at 22 59 37](https://user-images.githubusercontent.com/42740492/111562193-860eb900-8774-11eb-80ca-9b0790372fc2.png)

**Comment by harshavardhana** [comment] 2021-03-18 02:03
what is the server setup being used here? @arantesxyz

**Comment by arantesxyz** [comment] 2021-03-18 04:33
Minio: `minio/minio:latest`
Minio Console: `minio/console:latest`
SO: Ubuntu 20.04

They're both running on Docker on the same network. Even tho both are exposed to the outside world using a reverse proxy console communicate with minio internally.

![Screen Shot 2021-03-18 at 01 33 25](https://user-images.githubusercontent.com/42740492/111573795-f3791480-8789-11eb-98a1-da0860baceb4.png)

**Comment by github0null** [comment] 2021-04-02 13:11
I ran it in binary mode, and after I had followed the tutorial, I had the same problem.

```ini
system:  centos7.3
http server: nginx
Minio Console: minio/console:latest
```

***

I also can't create a bucket, it gives me an error every time I create a bucket.

![image](https://user-images.githubusercontent.com/43022536/113418294-c5d1d380-93f7-11eb-8fdf-72c17ddebf06.png)


This is the browser console log:

![image](https://user-images.githubusercontent.com/43022536/113418024-3b896f80-93f7-11eb-851b-f01f39586755.png)

**Comment by dvaldivia** [comment] 2021-04-05 15:46
@github0null do you see any output on the console detailing the error?

**Comment by dvaldivia** [comment] 2021-04-05 15:48
@arantesxyz @github0null is the MinIO deployment running in distributed mode or stand alone?

**Comment by dvaldivia** [comment] 2021-04-05 15:52
@github0null since your problem is creating a bucket, perhaps you have a different issue

**Comment by github0null** [comment] 2021-04-05 16:33
> @arantesxyz @github0null is the MinIO deployment running in distributed mode or stand alone?

stand alone

**Comment by github0null** [comment] 2021-04-05 16:35
> @github0null do you see any output on the console detailing the error?

Only the POST request error in the screenshot above, nothing more

**Comment by arantesxyz** [comment] 2021-04-06 11:42
> @arantesxyz @github0null is the MinIO deployment running in distributed mode or stand alone?

Standalone



> > @github0null do you see any output on the console detailing the error?
> 
> Only the POST request error in the screenshot above, nothing more

Mine is also only the one i reported, everything else works fine.

**Comment by Weilbyte** [comment] 2021-05-07 14:20
The issue is that the file name is not sent with the request for some reason, see (the 2nd request)
![image](https://user-images.githubusercontent.com/43392677/117463428-f30e2600-af4f-11eb-98c2-62144ba4392c.png)

I assume this has something to do with the first request failing (because of the `with_versions=true` parameter - the bucket does not have version support, and cannot due to running in standalone mode). @dvaldivia can you confirm?

**Comment by cb3inco** [comment] 2021-07-14 03:15
Same situation for me.

![image](https://user-images.githubusercontent.com/14948644/125555335-5d81488f-9350-40c3-8c75-7f229ee759f5.png)

**Comment by dvaldivia** [comment] 2021-07-22 23:19
what browser are you using @cb3inco ?

**Comment by bexsoft** [comment] 2021-07-23 00:13
This should be fixed in https://github.com/minio/console/pull/880 & https://github.com/minio/console/pull/889

**Closed by bexsoft** 2021-07-23 00:13 UTC

**Comment by cb3inco** [comment] 2021-07-23 10:25
> what browser are you using @cb3inco ?

Brave
