### ISSUE TITLE
Pagination in web UI

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/console#943] opened 2021-08-12 09:51 UTC
**Is your feature request related to a problem? Please describe.**

I know that it is not good practice to store a lot of object/subdirectories under bucket/directory but sometime it is unavoidable.
Currently I have about ~300 subfolders and ~1000 objects and it takes long time for Console's object browser or mc ls to preview them. I see that both of them try to load all "objects", but it is not always necessary so pagination can be good solution I think.

**Describe the solution you'd like**
Paginate list of items in buckets and dirs

**Describe alternatives you've considered**

**Additional context**

**Comment by krishadvani** [comment] 2022-09-22 14:04
Some of our paths/prefixes contain over 100K+ objects, which we cannot subdivide any further. The problem is that it makes an API call to list all the objects, which may cause a performance impact if accidentally clicked from the console. Further, the minio limits documentation specifies "Maximum number of objects returned per list objects request: 1000", however it seems to be ignoring that limit.

Any alternative solution to avoid a performance impact?

**Comment by bexsoft** [comment] 2022-09-23 18:09
Hi @krishadvani!

We are working on a fix for this

**Comment by krishadvani** [comment] 2022-09-24 02:26
Thanks, @bexsoft, we sincerely appreciate it.

**Closed** 2022-12-06 19:23 UTC
Labels: enhancement
