### ISSUE TITLE
Console dashboard shows offline drives incorrectly

### ISSUE THREAD

**Issue by tkg61** [minio/console#770] opened 2021-05-25 14:33 UTC
Updated to latest console (7.3) and minio (5-22) and new dashboard metrics are great! 

One of our clusters is showing 4 offline drives even though looking at the cluster via mc shows no offline drives in addition to prometheus showing no offline drives. Also 3 week uptime is false, was about 4 minutes...

![image](https://user-images.githubusercontent.com/3945114/119514996-7a76da00-bd43-11eb-82fb-11960d1fb591.png)

![image](https://user-images.githubusercontent.com/3945114/119515250-b3af4a00-bd43-11eb-9ff9-fecb3cea114d.png)

![image](https://user-images.githubusercontent.com/3945114/119516327-aba3da00-bd44-11eb-960b-c08fe81106f4.png)

There is another cluster that doesn't have this issue so i am wondering if i have missed something (same versions of software).

**Comment by bexsoft** [comment] 2021-07-29 23:35
Does the problem still persist with Console v8.0.1 & MinIO RELEASE.2021-07-27T02-40-15Z? 
Please let us know to take a look, Thank you!

**Comment by bexsoft** [comment] 2021-09-25 05:05
Closed as it seems issue is no longer present in recent versions of console. Please open a new ticket in case the issue is still seen

**Closed** 2021-09-25 05:05 UTC
Labels: bug, UI
