### ISSUE TITLE
Enhancement suggestion: Bring existing policies into "Assign policies"

### ISSUE THREAD

**Issue by udf2457** [minio/console#2270] opened 2022-08-25 08:14 UTC
At present, the behaviour of `Users -> User -> Assign policies` is that it does not bring in already assigned policies, you get presented with a list that is entirely unselected.

It would be much better UX if policies already assigned to the user were pre-selected.

**Comment by bpedersen2** [comment] 2022-08-30 07:43
duplicate of #2282 ?

**Closed** 2022-08-30 17:07 UTC
