### ISSUE TITLE
Can't download chinese name file from minio console

### ISSUE THREAD

**Issue by holmesian** [minio/console#1293] opened 2021-12-05 14:33 UTC
Still can't download file from minio console.

Chinese file name  will get an empty file  .  I use english file name normally.

     "content-disposition" filename get garbled code , "content-length"  0

<img width="680" alt="Screen Shot 2021-12-05 at 10 18 25 PM" src="https://user-images.githubusercontent.com/1128377/144750414-096ec0a8-1490-457f-b973-813fbafe8fdb.png">

The minio backend print error:

      2021/12/05 22:18:08 The specified key does not exist.
      2021/12/05 22:18:36 The specified key does not exist.
      2021/12/05 22:18:36 The specified key does not exist.

----

- Version used (minio --version): minio version RELEASE.2021-11-24T23-19-33Z
- Server setup and configuration:
- Operating System and version (uname -a): Linux home-pi 4.19.66-v7+ # 1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by Alevsk** [comment] 2021-12-06 06:19
@holmesian we are aware of the issue and we are working on a fix

**Comment by holmesian** [comment] 2021-12-06 09:06
Thank you. 

Look forward to solving.

**Comment by Alevsk** [comment] 2021-12-06 21:50
@holmesian first part of the issue is addressed by this PR https://github.com/minio/console/pull/1296, now you should be able to download and share your files

**Closed** 2021-12-06 21:49 UTC
Labels: bug
