### ISSUE TITLE
Settings UI is buggy in Safari

### ISSUE THREAD

**Issue by jpxd** [minio/console#606] opened 2021-02-18 14:30 UTC
Hi,
when trying to edit e.g. the cache settings in Safari, the settings won't show directly. One has to resize the window until they finally appear. This happens in all configuration pages for me.  In Google Chrome it works without problems.
Please see the attached video of the bug. Tested with the most current Docker image.

https://user-images.githubusercontent.com/10384363/108371382-fc63de00-71fd-11eb-89d0-91309b502cf7.mp4

**Comment by dvaldivia** [comment] 2021-02-19 19:56
Hi @jpxd I'm also on macOS 11.2.1 but I don't see this problem on Safari, are you by any chance on an `m1` mac?

**Comment by dvaldivia** [comment] 2021-02-19 19:58
Which version of the console are you using? @jpxd

**Comment by jpxd** [comment] 2021-02-19 21:20
Hi, I am on macOS 11.2.1 (no M1, 2019 MacbookPro) with Safari 14.0.3.
I just tested again with the newest console release (minio/console:v0.6.0 from DockerHub) and the problem persists.
The `region` editor opens without problems, the `cache` editor always glitches and gets stuck somewhere in the transition (overshoots in the horizontal transition from right to left?) and is only fixed by resizing the window.

Here are two more screenshots:
<img width="1144" alt="Bildschirmfoto 2021-02-19 um 22 14 00" src="https://user-images.githubusercontent.com/10384363/108562503-3cab8500-7300-11eb-9f43-3952e29ec23a.png">
<img width="722" alt="Bildschirmfoto 2021-02-19 um 22 15 00" src="https://user-images.githubusercontent.com/10384363/108562506-3ddcb200-7300-11eb-8be0-04a4a6206d37.png">

**Comment by dvaldivia** [comment] 2021-02-19 22:12
That's so weird, I'm on the same Safari and I don't get that bug, do you have any extensions on Safari?

<img width="1352" alt="Screen Shot 2021-02-19 at 2 12 08 PM" src="https://user-images.githubusercontent.com/18384552/108567148-84a8b880-72bc-11eb-94e4-892cb599b5ef.png">

**Comment by dvaldivia** [comment] 2021-02-19 22:13
@jpxd can you try deleting your cache? Open Developer tools and disable cache for the website, and refresh

**Comment by jpxd** [comment] 2021-02-19 22:21
I have the Ghostery Lite extension installed but I disabled it for testing and restarted Safari - without success. Deleting/disabling the cache didn't help either. 😕

**Comment by dvaldivia** [comment] 2021-02-19 22:27
@jpxd I also have ghostery so I don't think that's the reason

I can only repro the behavior when resizing the window, but it resets as soon as the resize is done




https://user-images.githubusercontent.com/18384552/108568215-870c1200-72be-11eb-9d91-b87bf5191a2f.mov

**Comment by bexsoft** [comment] 2021-03-02 21:23
This issue is related to an incompatibility with Safari & scrollIntoView method. I was able to reproduce it only in sections were csv selector is present for settings page. Will work on a fix for this

**Comment by bexsoft** [comment] 2021-03-02 23:13
Fixed in #622

**Closed** 2021-03-04 22:53 UTC
Labels: UI, WIP, bug
