### ISSUE TITLE
MinIO screen is not displayed with Login with SSO button

### ISSUE THREAD

**Issue by raviepgithub** [minio/console#3278] opened 2024-04-01 17:02 UTC
MinIO screen is not displayed with Login with SSO button though keycloak details are specified in Tencent Kubernetes Engine platform.

## Expected Behavior
Login with SSO button should have been displayed.

## Current Behavior
MinIO login screen is displayed with username/password textboxes instead.

## Possible Solution
Some of the environment variables 

## Your Environment
* MinIO helm chart is installed on Tencent Kubernetes Engine.
* MinIO version used (`minio --version`): RELEASE.2022-09-17T00-09-45Z

**Comment by cesnietor** [comment] 2024-04-15 16:41
@raviepgithub  please share more information on your keycloak configuration and more steps to reproduce otherwise is hard for us to tell.
Please also make sure you are following this: https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html

**Comment by cesnietor** [comment] 2024-06-24 16:36
closing due to innactivity, please open a new one with more details if the issue persists.

**Closed by cesnietor** 2024-06-24 16:36 UTC
Labels: community, triage
