### ISSUE TITLE
Access Keys without description created through the console doesn't seem to work

### ISSUE THREAD

**Issue by kriansa** [minio/console#3224] opened 2024-02-04 04:42 UTC
I'm trying to create new access keys for a specific user on a bucket. If I create them using `mc admin`, it works regardless of whether I add description or not.

When adding it through the Console interface, unless I add a description, it gets into this state where all requests using it will fail due to anauthorized errors.

## Expected Behavior
I expect the keys created without description to work just like the ones with description.

## Current Behavior
They currently don't.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Create an access key for any user to access a bucket without a description
2. Try to access it with e.g. `mc alias set myserver http://localhost:9000 MYACCESSKEY MYSECRET` and then `mc ls myserver`
3. Now edit this key adding a description
4. `mc ls myserver` should work

## Context
N/A

## Regression
I haven't tested it on previous versions.

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2024-01-31T20-20-33Z
* Server setup and configuration: Installed on a Podman container
* Operating System and version (`uname -a`): `Linux e1f884f74244 5.14.0-378.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Oct 19 18:39:36 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment] 2024-02-04 04:46
Duplicate of https://github.com/minio/minio/issues/18939 already fixed in master awaiting release.

**Closed by harshavardhana** 2024-02-04 04:46 UTC
Labels: community, triage
