### ISSUE TITLE
Console : restrict GUI when using as a gateway to azure

### ISSUE THREAD

**Issue by christopheblin** [minio/console#1280] opened 2021-12-02 14:07 UTC
## Expected Behavior

I am using minio as a gateway to azure storage

Before, I was using minio/minio:RELEASE.2021-06-07T21-40-51Z

In this release, the File browser was the only GUI

Now, I've upgraded minio and I have a magnificient Console (this is not ironic, I really think that this console is way better than the previous GUI when you have a minio cluster and not a gateway)

However, all menus are useless except "Buckets" when minio is used as a gateway

Is there a possiblity for the console to be aware of the "gateway" situation, and in this case to not display irrelevant menus ?

## Context

Minio used as a gateway for azure storage

## Regression

No

## Your Environment

* Version used (`minio --version`): docker minio/minio RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: azure gateway
* Operating System and version (`uname -a`): see focker

**Comment by dvaldivia** [comment] 2021-12-02 21:36
I tested with azure blob and some of the menus such as `users` and `iam policies` worked just fine, although they are ephemeral, if you want to restrict the UI you should create a policy that only allows for bucket exploration and assign it to a user.

The current list of menus during gateway does serve a purpose so I think we won't be removing them unless we find a valid use case for when a menu item is useless

**Comment by dvaldivia** [comment] 2021-12-02 21:37
@christopheblin you are seeing all the menus since the root credentials (azure account) is used to login, just create users with less priviledges to restrict the menus

**Closed by dvaldivia** 2021-12-02 21:37 UTC

**Comment by christopheblin** [comment] 2021-12-03 08:00
@dvaldivia thanks for the answer, I appreciate

> although they are ephemeral

What does it mean ? They do not survive a pod restart ?

> create a policy that only allows for bucket exploration

I tried to create a user with readonlypolicy but he still has the Service accounts menu

![Capture d’écran 2021-12-03 à 08 57 43](https://user-images.githubusercontent.com/11044877/144566415-d0c4b290-cc78-4574-addc-05739e9aa350.png)

I cannot see what I did wrong here, the policy is not mentionning anything about service account and I do not see that in the docs either. Maybe this is a bug ?

**Comment by harshavardhana** [comment] 2021-12-03 08:03
> What does it mean ? They do not survive a pod restart ?
> 

Yes to persist policies in gateway you need etcd.

**Comment by harshavardhana** [comment] 2021-12-03 08:04
> I tried to create a user with readonlypolicy but he still has the Service accounts menu and he doesnot see the buckets

ServiceAccounts are implicit for all users to have access - this is working as intended.

**Comment by christopheblin** [comment] 2021-12-03 08:05
@harshavardhana Thanks for the 2 pointers, I'll look into them

What about the problem about not seeing the buckets ? Do you have an idea ?

**Comment by christopheblin** [comment] 2021-12-03 08:16
Please note that I have enabled the s3:ListAllMyBuckets in the readonly policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by harshavardhana** [comment] 2021-12-03 09:05
> Please note that I have enabled the s3:ListAllMyBuckets in the readonly policy

Did you associate this policy with the user? @christopheblin

**Comment by christopheblin** [comment] 2021-12-03 09:38
@harshavardhana Thanks for the near real time support, this is awesome !

Yes, the policy is associated to the user

![Capture d’écran 2021-12-03 à 10 25 23](https://user-images.githubusercontent.com/11044877/144578581-16313aed-70c2-4dd5-8123-8cb6a382eeb6.png)

I do not have the mc cli right now, I only use the web console to manipulate the buckets up to now (and some softwares are using the S3 API successfully with the azure storage account owner key/secret as identifiers)

Do you need me to install the CLI in order to try the commands ?

Note that if I try to log in as the 'viewer' user and i directly go to https://xxx/buckets/mybucket/browse it says "This location is empty, please try uploading a new file" so it does not seem to be related only to the ListAllMyBuckets permission

Maybe the policy is missing another action to list the contents of a bucket ? Or maybe the problem is that the policies are not correctly mapped when minio is used as an azure storage account gateway ?
