### ISSUE TITLE
Prometheus Fall Back isn`t working

### ISSUE THREAD

**Issue by RedL1ghtning** [minio/console#2829] opened 2023-05-23 15:43 UTC
Greetings!

I have Minio and VictoriaMetrics  clusters. Trying set up monitoring in Minio console.

When i set ```MINIO_PROMETHEUS_URL``` to http://vm-cluster:8481 - healthcheck work fine, but metrics isn`t work. Victoriametrics logs: 
```
2023-05-23T15:00:18.267Z        warn    VictoriaMetrics/app/vmselect/main.go:277        remoteAddr: "MINIO_IP:PORT"; requestURI: /api/v1/label/disk/values; auth error: cannot parse accountID from "v1": strconv.ParseUint: parsing "v1": invalid syntax
```
When i sey ```MINIO_PROMETHEUS_URL``` to http://vm-cluster:8481/select/0/prometheus - healtcheck isn`t work with error "Prometheus URL is unreachable". Victoriametrics logs:
```
2023-05-23T15:09:13.353Z        warn    VictoriaMetrics/lib/httpserver/httpserver.go:343        remoteAddr: "MINIO_IP:PORT"; requestURI: /select/0/prometheus/-/healthy; unsupported path requested: "/select/0/prometheus/-/healthy"
```
In this lines addef fall back mechanism for similar problems, but something goes wrong:
https://github.com/minio/console/blob/920fc7d937d25dfa466461d238d23df4e6ac757b/restapi/admin_info.go#L987-L1011

Seems like some fuctions didn`t use ```testPrometheusURL``` inside

**Comment by PolinaVens** [comment] 2023-10-11 08:31
Is there any update on the issue? I have a similar problem in MinIO VERSION 2023-10-07T15:07:38Z

**Comment by ngc6166** [comment] 2023-11-22 18:30
Hi! I have the same in RELEASE.2023-11-20T22-40-07Z.

**Comment by rpardini** [comment] 2024-01-02 15:59
Same with `DEVELOPMENT.2023-12-23T07-19-11Z`  (as provided by Bitnami's minio Helm Chart).
References https://github.com/minio/console/issues/1373 and https://github.com/minio/console/pull/1431

**Comment by dvaldivia** [comment] 2024-01-25 00:43
This is fixed now, please reopen if it keeps happening

**Comment by DANic-git** [comment] 2024-02-26 10:01
Reproduce in RELEASE.2024-02-24T17-11-14Z

**Comment by autokilla47** [comment] 2024-05-23 14:52
Reproduce in RELEASE.2024-05-10T01-41-38Z

**Comment by cniackz** [comment] 2024-08-28 22:46
First of all, this isn’t Prometheus, and VictoriaMetrics does not use scrape_configs in the same way Prometheus does. It is also expected that the health check will fail for http://vm-cluster:8481/select/0/prometheus, as including select/0/prometheus in the URL will not match the /-/healthy endpoint. This is reflected in the following changelog entry:

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1833

```
./docs/changelog/CHANGELOG_2021.md: * FEATURE: Expose `/-/healthy` and `/-/ready` endpoints similar to Prometheus. This improvement facilitates integration with third-party solutions that rely on these endpoints. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1833).
```

When I last tested this feature using [this guide](https://github.com/cniackz/public/wiki/How-to-configure-Prometheus-and-MinIO-in-k8s), I encountered no issues, although I haven’t tested VictoriaMetrics myself.

If PR #956 has broken this feature or if VictoriaMetrics has changed, it would be helpful to identify which commit caused the issue or how VictoriaMetrics is configured. This seems to be more of an integration issue with VictoriaMetrics rather than a problem with Prometheus configuration. We need to discuss internally whether we should continue supporting VictoriaMetrics integration.

**Comment by ramondeklein** [comment] 2024-08-29 01:10
VictoriaMetrics doesn’t seem to implement the Prometheus health-checks. We support Prometheus, but don’t support 99% compatible products. 

I think it would make more sense to request VictoriaMetrics to support the missing endpoint. It claims to be Prometheus compatible, so it should support it.

**Closed by ramondeklein** 2024-08-29 01:10 UTC
Labels: community
